import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F3F5FE',
  },
  backgroundLayerTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 220,
    backgroundColor: '#6C63FF',
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
  },
  backgroundLayerGlow: {
    position: 'absolute',
    top: 70,
    right: -40,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: '#A09BFF',
    opacity: 0.35,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 28,
    paddingTop: 8,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  brand: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: 1.8,
  },
  subtitle: {
    color: '#E8E7FF',
    marginTop: 2,
    fontSize: 13,
    letterSpacing: 0.6,
  },
  cartBadge: {
    minWidth: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F9B51C',
    paddingHorizontal: 10,
  },
  cartBadgeText: {
    color: '#1B1B1B',
    fontSize: 16,
    fontWeight: '900',
  },
  totalBar: {
    marginTop: 4,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#111827',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 5,
  },
  totalBarLabel: {
    color: '#596173',
    fontSize: 14,
    fontWeight: '600',
  },
  totalBarValue: {
    color: '#111827',
    fontSize: 20,
    fontWeight: '900',
  },
  categoriesWrap: {
    paddingVertical: 18,
  },
  categoryChip: {
    marginRight: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  categoryChipActive: {
    backgroundColor: '#111827',
  },
  categoryLabel: {
    color: '#4B5563',
    fontSize: 13,
    fontWeight: '700',
  },
  categoryLabelActive: {
    color: '#FFFFFF',
  },
  gestureHelp: {
    marginBottom: 10,
    color: '#5B6383',
    fontSize: 12,
    fontWeight: '600',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 14,
  },
  cardSlot: {
    marginBottom: 4,
  },
  swipeHint: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    borderRadius: 20,
    paddingHorizontal: 12,
  },
  addHint: {
    right: 0,
    backgroundColor: '#DCFCE7',
  },
  removeHint: {
    left: 0,
    backgroundColor: '#FEE2E2',
  },
  swipeHintText: {
    color: '#1F2937',
    fontSize: 12,
    fontWeight: '800',
  },
  productCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.11,
    shadowRadius: 14,
    elevation: 6,
  },
  cardImageWrap: {
    height: 124,
  },
  cardImage: {
    width: '100%',
    height: '100%',
    opacity: 0.95,
  },
  cardBody: {
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  cardCategory: {
    fontSize: 11,
    color: '#6B7280',
    textTransform: 'uppercase',
    fontWeight: '700',
    marginBottom: 4,
  },
  cardTitle: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
  },
  cardFooter: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardPrice: {
    color: '#0F172A',
    fontSize: 18,
    fontWeight: '900',
  },
  quickAddBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickAddLabel: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 17,
    marginTop: -1,
  },
  qtyLabel: {
    marginTop: 8,
    color: '#4F46E5',
    fontSize: 12,
    fontWeight: '700',
  },
});
